# Site settings
title: "Few, but ripe..."
author: Brandon Williams
email: mbw234@gmail.com
description: > #
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: mbrandonw
github_username:  mbrandonw

# Build settings
markdown: kramdown
