# Site settings
title: "Few, but ripe..."
author: Brandon Williams
email: mbw234@gmail.com
description: > #
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.fewbutripe.com" # the base hostname & protocol for your site
twitter_username: mbrandonw
github_username:  mbrandonw

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
